# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class AddressbookPostRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AddressbookPostRequest - a model defined in OpenAPI

        addrtype: The addrtype of this AddressbookPostRequest [Optional].
        city: The city of this AddressbookPostRequest [Optional].
        country: The country of this AddressbookPostRequest [Optional].
        person_uuid: The person_uuid of this AddressbookPostRequest [Optional].
        state: The state of this AddressbookPostRequest [Optional].
        street: The street of this AddressbookPostRequest [Optional].
    """

    addrtype: Optional[str] = Field(alias="addrtype", default=None)
    city: Optional[str] = Field(alias="city", default=None)
    country: Optional[str] = Field(alias="country", default=None)
    person_uuid: Optional[str] = Field(alias="person_uuid", default=None)
    state: Optional[str] = Field(alias="state", default=None)
    street: Optional[str] = Field(alias="street", default=None)

AddressbookPostRequest.update_forward_refs()
